config/routes.rb
Aid::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/sign_in', :to => 'devise/sessions#new', :as => 'sign_in'
  end

  def monthly_statements_resources
    resources :monthly_statements do
      member do
        post :calculate
        get :bill
        get :payment
      end
      resources :journal_entries, :controller => 'monthly_statements/journal_entries'
    end
  end

  ########################################################### Headquarter

  namespace :hq do
    get '/' => 'home#index', :as => :root

    resources :bss do
      collection do
        get :left
      end

      member do
        get :resign
        get :leave
        post :leave
        post :activate
      end

      resources :bs_users, :controller => 'bss/bs_users' do
        member do
          match :change_password
        end
      end

      resources :students, :controller => 'bs_students', :only => [:index]

      resources :monthly_statements, :controller => 'bss/monthly_statements', :except => [:update, :destroy] do
        post 'calculate', :on => :member
        resources :adjusting_entries, :controller => 'bss/monthly_statements/adjusting_entries'
        resources :journal_entries, :controller => 'bss/monthly_statements/journal_entries', :only => [:index, :show]
      end

      resource :bank_account, :controller => 'bss/bank_accounts' do
        member do
          get :complete
        end
      end

    end
    resources :bs_users
    resources :users
    resources :tutors do
      collection do
        get :left
        get :absent
        post :create_from_app_form
      end
      member do
        match :leave
        post :come_back
        post :become_regular
        post :become_beginner
        get :change_password
        put :change_password
      end

      resource :special, :controller => :tutor_specials, :only => [:show, :update]

      resource :membership_cancellation, :controller => :tutor_membership_cancellations, :path_names => {:new => :form}

      resources :monthly_statements, :controller => 'tutors/monthly_statements' do
        post 'calculate', :on => :member
        resources :adjusting_entries, :controller => 'tutors/monthly_statements/adjusting_entries'
        resources :journal_entries, :controller => 'tutors/monthly_statements/journal_entries', :only => [:index, :show]
      end

      resources :teaching_subjects, :controller => 'tutors/teaching_subjects' do
        collection do
          put '/', action: 'update'
          get :edit
        end
      end

      resource :type, controller: :tutor_types

      resource :bank_account, :controller => 'tutors/bank_accounts'
    end

    resources :my_students, :only => :index

    resources :students do
      collection do
        get :left
        get :billing
      end
      member do
        get :history
        match :leave
        post :come_back
        get :change_password
        put :change_password
      end

      resource :membership_cancellation, :controller => :student_membership_cancellations, :path_names => {:new => :form}

      resource :address, :controller => 'students/addresses'

      resources :basic_lesson_infos, :controller => 'students/basic_lesson_infos' do
        member do
          post :extend
          post :turn_off_auto_extension
          post :turn_on_auto_extension
          post :supply
        end
        resources :lessons, :controller => 'students/basic_lesson_infos/lessons', :only => [:index, :show]
      end

      resources :optional_lessons, :controller => 'students/optional_lessons'

      resources :journal_entries, :controller => 'students/journal_entries' do
        get ':year/:month', :action => :month, :as => :month, :on => :collection
      end
      resources :ledgers, :controller => 'students/ledgers', :only => [:index] do
        collection do
          post ':year/:month/calculate', :action => :calculate
          get ':year/:month', :action => :month, :as => :month
          get ':year', :action => :year, :as => :year
        end
      end
      resources :monthly_statements, :controller => 'students/monthly_statements', :only => [:index, :show, :create, :edit] do
        member do
          post :calculate
        end
        resources :adjusting_entries, :controller => 'students/monthly_statements/adjusting_entries'
        resources :journal_entries, :controller => 'students/monthly_statements/journal_entries', :only => [:index, :show]
      end

      resources :monthly_usages, :controller => 'students/monthly_usages', :only => [:index, :show] do
        get ':year/:month', action: 'year_month', :on => :collection
        post :calculate, :on => :member
      end

      resource :coach, :controller => :student_coaches, :only => [:show]
    end

    resources :trial_students do
      member do
        get :change_password
        put :change_password
      end

      resources :lessons, :controller => :trial_student_lessons
    end

    resources :trial_lessons do
      resources :forms, :controller => :trial_lesson_forms do
        member do
          post :cancel
        end
      end
    end

    resources :parents do
      collection do
        get :left
      end
      member do
        match :leave
        get :activate
        post :activate
        get :change_password
        put :change_password
      end

      resource :membership_cancellation, :controller => :parent_membership_cancellations, :path_names => {:new => :form}
    end

    resources :coaches do
      collection do
        get :left
      end
      member do
        post :deactivate
        post :activate
        get :change_password
        put :change_password
      end
    end

    resources :tutor_interviews

    resources :lessons do
      collection do
        get :calendar
        get :under_request
        get :history
        get :pending
        get :not_started
      end
      member do
        match :cancel, :via => [:get, :post]
        get :room_as_tutor
        get :room_as_student
        get :room
        match :change_schedule
        post :cancel_request
        get :accounting
        get :updated_at
      end

      get :materials, :controller => :lesson_materials, :action => :lesson
    end

    resources :basic_lesson_infos do
      collection do
        get :pending
        get :rejected
        get :shared
        get :closed
      end
      member do
        match :stop
        post :turn_off_auto_extension
        post :turn_on_auto_extension
        post :cancel_request
        get  :close
        post :close
        get  :status
      end
      resources :forms, :controller => 'basic_lesson_infos/forms' do
        post :cancel, :on => :member
      end
      resources :lessons, :controller => 'basic_lesson_infos/lessons' do
        collection do
          post :supply
          post :cancel_selected
        end
        member do
          get :room_as_tutor
          get :room_as_student
          post :cancel
          match :change_schedule
        end
      end

      resources :students, :controller => 'basic_lesson_infos/students', :path_names => {:new => 'add'}
    end

    resources :optional_lessons do
      resources :forms, :controller => 'optional_lessons/forms' do
        member do
          post :cancel
        end
      end
    end

    resources :awards

    resources :tutor_app_forms do
      collection do
        get :processed
      end
      member do
        post :create_tutor
        get :account_created
        post :reject
      end
      resource :tutor, :controller => 'tutor_app_forms/tutors'
    end

    resources :bs_app_forms do
      collection do
        get :processed
      end
      member do
        post :create_user
        post :reject
        get  :registered
      end
      resource :bs, :controller => 'bs_app_forms/bss' do
        resource :bs_user, :controller => 'bs_app_forms/bss/bs_users', :only => [:show, :new, :create]
      end
    end

    resources :document_cameras do
      collection do
        get :yearly
        get :monthly
        get :daily
        get :file
      end
    end
    resources :messages do
      member do
        get :reply
      end
      resources :replies, controller: :message_replies
    end
    resources :my_messages do
      resources :files, controller: :my_message_files
    end
    resources :all_messages, :only => [:index, :show]

    resources :lesson_reports do
      member do
        get :prev
        get :next
      end
    end
    resources :cs_sheets
    resources :exams, :only => :index do
      collection do
        get ':grade_id/:subject_id/:year/:month/new', :action => :new
        get ':grade_id/:subject_id/:year/:month/file', :action => :file
        get ':grade_id/:subject_id/:year/:month/:paper_id', :action => :paper
        get ':grade_id/:subject_id/:year/:month', :action => :show
        post ':grade_id/:subject_id/:year/:month', :action => :create
        get ':grade_id/:subject_id/:year', :action => :year
        get ':grade_id/:subject_id', :action => :subject
        get ':grade_id', :action => :grade
      end
    end

    get :settings, :controller => :settings, :action => :index
    resource :system_settings
    resource :lesson_settings, :only => [:show, :edit, :create]
    resource :free_mode_settings
    resources :switching_payment_method_users
    resources :charge_settings

    match 'calendar(/:year(/:month))' => 'calendars#lessons', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
    resources :textbooks do
      member do
        get :image
      end
      resource :answer_book, :controller => 'textbooks/answer_books'
    end
    resources :users do
      member do
        match :change_password
      end
    end
    resources :subjects
    resources :journal_entries

    resources :monthly_statements do
      member do
        post :calculate_all
        post :calculate
        get  :yucho
      end

app/controllers/bs/all_coach_messages_controller.rb
class Bs::AllCoachMessagesController < UserMessagesController
  bs_user_only
  layout 'with_sidebar'

  def index
    query = BsMessageQuery.new(current_user)
    @messages = query.all_coach_messages.page(params[:page])
  end

  def show
    query = BsMessageQuery.new(current_user)
    @message = query.all_coach_messages.find_by_id(params[:id])
    if @message.nil?
      redirect_to action: :index
    end
  end
end

app/controllers/bs/all_student_messages_controller.rb
class Bs::AllStudentMessagesController < UserMessagesController
  bs_user_only
  layout 'with_sidebar'

  def index
    query = BsMessageQuery.new(current_user)
    @messages = query.messages_between_students_and_tutors.page(params[:page])
  end

  def show
    query = BsMessageQuery.new(current_user)
    @message = query.messages_between_students_and_tutors.find_by_id(params[:id])
    if @message.nil?
      redirect_to action: :index
    end
  end
end

app/controllers/bs/bank_accounts_controller.rb
class Bs::BankAccountsController < BankAccountsController
  bs_user_only

  private

  def subject
    current_user.organization
  end
end

app/controllers/bs/basic_lesson_infos/forms_controller.rb
class Bs::BasicLessonInfos::FormsController < BasicLessonInfoFormsController
  bs_user_only

  private
    def finish_wizard_path
      pending_bs_basic_lesson_infos_path
    end

    def redirect_path_on_cancellation
      bs_basic_lesson_infos_path
    end

    def search_tutors(options)
      @tutor_search = TutorSearchForBsUsers.new(options)
      @tutor_search.execute
    end

    def find_default_students(exclusions=[])
      students = current_user.students_for_lesson(@basic_lesson_info).only_active
      if exclusions.empty?
        students
      else
        students.where('users.id NOT IN (?)', exclusions)
      end
    end
end

app/controllers/bs/basic_lesson_infos/lessons_controller.rb
class Bs::BasicLessonInfos::LessonsController < BasicLessonInfoLessonsController
  bs_user_only
end

app/controllers/bs/basic_lesson_infos/students_controller.rb
class Bs::BasicLessonInfos::StudentsController < BasicLessonInfoStudentsController
  bs_user_only

  def index
    redirect_to redirect_path
  end

  private

    def redirect_path
      bs_basic_lesson_info_path(@basic_lesson_info)
    end
end

app/controllers/bs/basic_lesson_infos_controller.rb
# coding:utf-8

class Bs::BasicLessonInfosController < BasicLessonInfosController
  bs_user_only
  layout 'with_sidebar'

  def shared
    if params[:q]
      search = BasicLessonSearch.new(params.merge(shared_lesson: true))
      @basic_lesson_infos = search.execute
    else
      # 全同時レッスンを対象とする
      @basic_lesson_infos = BasicLessonInfo.shared.only_active.order('created_at DESC').page(params[:page])
    end
  end

  def new
    @basic_lesson_info = BasicLessonInfo.new # dummy
  end

  def create
    @basic_lesson_info = basic_lesson_class(params[:type]).new(creator:current_user)
    if @basic_lesson_info.save
      redirect_to forms_path
    else
      render action: 'new'
    end
  end

  def show
    # 自分のところと関係のない受講者の分も閲覧できる必要がある。
    @basic_lesson_info = BasicLessonInfo.find_by_id(params[:id])
    if @basic_lesson_info.nil?
      render template:'basic_lesson_infos/nonexistent_lesson'
    end
  end

  # 決定前のレッスンをキャンセルする
  def cancel
    @basic_lesson_info = current_user.basic_lesson_infos.find(params[:id])
    if @basic_lesson_info.cancel
      redirect_to({action:'index'}, notice:t('lesson.message.request_canceled'))
    else
      redirect_to({action:'show'}, notice:t('lesson.message.failed_to_cancel'))
    end
  end

  # basic_lesson_infos/:id/supply
  def supply
    @basic_lesson_info = basic_lesson_infos.find(params[:id])
    @basic_lesson_info.supply_lessons
    redirect_to action:"show"
  end

  def lessons
    @basic_lesson_info = basic_lesson_infos.find(params[:id])
    @lessons = @basic_lesson_info.lessons.future.order("start_time").page(params[:page])
  end

  def stop
    @basic_lesson_info = basic_lesson_infos.find(params[:id])
    if request.get?
      @basic_lesson_info.final_day = Date.today
    else
      @basic_lesson_info.stop_in_month(params[:date][:year], params[:date][:month])
      if @basic_lesson_info.save
        redirect_to action:"show"
      else
        # do nothing
      end
    end
  end

  def turn_off_auto_extension
    @basic_lesson_info = basic_lesson_infos.find(params[:id], readonly: false)
    @basic_lesson_info.turn_off_auto_extension
    redirect_to action:"show"
  end

  def turn_on_auto_extension
    @basic_lesson_info = basic_lesson_infos.find(params[:id], readonly: false)
    @basic_lesson_info.turn_on_auto_extension
    redirect_to action:"show"
  end

  private

    def basic_lesson_infos
      current_user.basic_lesson_infos.only_complete
    end

    def new_basic_lesson_info
      BasicLessonInfo.new do |basic_lesson_info|
        basic_lesson_info.creator = current_user
      end
    end

    def forms_path
      bs_basic_lesson_info_forms_path(@basic_lesson_info)
    end
end

app/controllers/bs/basic_lessons_controller.rb
class Bs::BasicLessonsController < ApplicationController
  bs_user_only
  layout 'with_sidebar'

  def new
    @students = current_user.students.only_active.page(params[:page])
  end
end

app/controllers/bs/bss_controller.rb
class Bs::BssController < ApplicationController
  bs_user_only
  block_coach only: [:edit, :update]
  layout 'with_sidebar'

  def show
    @bs = current_user.organization
  end

  def leave
    @bs = current_user.organization
  end

  def edit
    @bs = current_user.organization
  end

  def update
    @bs = current_user.organization
    if @bs.address
      @bs.address.attributes = params[:address]
    else
      @bs.build_address = params[:address]
    end
    if @bs.update_attributes(params[:bs])
      redirect_to action:'show'
    else
      render 'edit'
    end
  end
end

app/controllers/bs/calendar_controller.rb
class Bs::CalendarController < ApplicationController
  bs_user_only
  layout "plain"

  def index
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i
    @shown_month = Date.civil(@year, @month)
    @event_strips = Lesson.event_strips_for_month(@shown_month,
                                                  :include => :students,
                                                  :conditions => {
                                                    :users => {:organization_id => current_user.organization_id},
                                                    :show_on_calendar => true
                                                  })
    render layout:nil if request.xhr?
  end
end

app/controllers/bs/coach_messages_controller.rb
class Bs::CoachMessagesController < UserMessagesController
  bs_user_only
  layout 'with_sidebar'

  before_filter :prepare_coach

  def index
    query = BsMessageQuery.new(current_user)
    @messages = query.coach_messages(@coach).page(params[:page])
  end

  def show
    query = BsMessageQuery.new(current_user)
    @message = query.coach_messages(@coach).find_by_id(params[:id])
    if @message.nil?
      redirect_to action: :index
    end
  end

  private
    def prepare_coach
      @coach = current_user.organization.coaches.find_by_id(params[:coach_id])
    end
end

app/controllers/bs/cs_sheets_controller.rb
class Bs::CsSheetsController < CsSheetsController
  bs_user_only
end

app/controllers/bs/home_controller.rb
class Bs::HomeController < UserHomeController
  bs_user_only
end

app/controllers/bs/meetings/forms_controller.rb
class Bs::Meetings::FormsController < MeetingFormsController
  bs_user_only

  private

    def finish_wizard_path
      scheduling_bs_meetings_path
    end
end

app/views/bs/students/_breadcrumbs.html.haml
%ul.breadcrumb
  %li
    =link_to_unless_current t("titles.students"), bs_students_path
  -if @student
    =render 'shared/breadcrumb_item', text:t('titles.student'), url:bs_student_path(@student)
    -if @basic_lesson_info
      =render 'shared/breadcrumb_item', text:t('titles.basic_lesson_infos'), url:bs_student_basic_lesson_infos_path(@student)
      =render 'shared/breadcrumb_item', text:t('titles.basic_lesson_info'), url:bs_student_basic_lesson_info_path(@student, @basic_lesson_info)
      -if @lessons
        =render 'shared/breadcrumb_item', text:t("titles.lessons")

app/views/bs/students/_explanation.ja.html.haml
%p 受講者を退会します。
.alert
  %ul
    %li 退会をしてもアカウントは残ります。
    %li 残っているレッスンは削除されます

app/views/bs/students/_menu.html.haml
.button-menu
  -if @student
    =link_to t('common.basic_lessons'), bs_student_basic_lesson_infos_path(@student), class: 'btn btn-small'
    =link_to t('student.coach'), bs_student_coach_path(@student), class: 'btn btn-small'
    =link_to t('student_messages.titles.index'), bs_student_messages_path(@student), class: 'btn btn-small'

app/views/bs/students/_nav_tab.html.haml
%ul.nav.nav-tabs
  =render "nav_tab_item", text:t("titles.students"), path:bs_students_path
  =render "nav_tab_item", text:t("titles.left_students"), path:left_bs_students_path

app/views/bs/students/edit.html.haml
=content_for :subheader do
  =render "breadcrumbs"

%h1=title t("titles.edit_student")

=form_for @student, url:bs_student_path(@student), html:{name:"student", novalidate:true} do |f|
  =render "validation_errors", model:@student
  %table.table
    %tr
      %th=t("common.full_name")
      %td
        .field.full_name
          =f.label :last_name
          =f.text_field :last_name
        .field.full_name
          =f.label :first_name
          =f.text_field :first_name
    %tr
      %th=f.label :user_name
      %td=f.text_field :user_name, :required => true, :readonly => true
    %tr
      %th=f.label :nickname
      %td=f.text_field :nickname, :required => true
    %tr
      %th=f.label :birthday
      %td=f.date_select :birthday, {start_year: 1900, end_year: Date.today.year}, class:"span2"
    %tr
      %th=f.label :sex
      %td
        =f.radio_button :sex, "male"
        =f.label :sex_male, t("common.male")
        =f.radio_button :sex, "female"
        =f.label :sex_female, t("common.female")
    %tr
      %th=f.label :phone_number
      %td
        =f.telephone_field :phone_number, :required => true
        .help=t('messages.hankaku_only')
    %tr
      %th=t("common.address")
      %td=render "addresses/form", address:@student.address
    =fields_for(@student.student_info) do |sf|
      %tr
        %th=sf.label :grade_id
        %td=sf.select :grade_id, options_for_select(Grade.order_by_grade.map{|g| [grade(g), g.id]}), {}, class:"span2"
      %tr
        %th=sf.label :academic_results
        %td=sf.text_field :academic_results, class:"span5"
  .form-actions.buttons
    =img_submit "common.send"

app/views/bs/students/index.html.haml
=content_for :tabmenu do
  =render "nav_tab"

%h1=title t("titles.students")

=render "menu"

-if @students.blank?
  = t('common.not_found')
-else
  =render layout: 'students/students_for_bs_user', locals:{students:@students} do |student|
    =link_to bs_student_path(student), class: 'btn btn-small btn-primary' do
      %i.icon-signin
      =t('common.detail')
    =link_to bs_student_lesson_reports_path(student), class: 'btn btn-small' do
      %i.icon-file-alt
      =t('common.report')
    =link_to new_bs_my_message_path(recipients:student.id), class: 'btn btn-small' do
      %i.icon-envelope-alt
      =t('common.send_message')
  =paginate(@students)

app/views/bs/students/leave.html.haml
=content_for :subheader do
  =render "breadcrumbs"

%h1=title t("common.resign")
=render "menu"
=render "explanation"
%section
  %h3=t("titles.student")
  =render "users/user", user:@student
.buttons
  = img_link_to "common.resign", {:id => @student, :action => :leave}, method:"post", data:{confirm:t("messages.confirm_to_leave")}

app/views/bs/students/left.html.haml
=content_for :tabmenu do
  =render "nav_tab"

%h1=title t("titles.students")

=render "menu"

-if @students.blank?
  = t('common.not_found')
-else
  =render layout:"students/students", locals:{students:@students} do |student|
    =img_link_to "common.detail", bs_student_path(student), class:"small"
  =paginate(@students)

app/views/bs/students/show.html.haml
=content_for :subheader do
  =render "breadcrumbs"

%h1=title t("titles.student")

=render "bs/students/menu"

=render "students/student", student:@student

%section
  %h2=t("common.charge_settings")
  =render "students/charge_settings", student:@student

%section
  %h2=t("common.favorite_tutor")
  -if @student.favorite_tutors.blank?
    =t('common.not_found')
  -else
    =render "students/favorite_tutors", tutors:@student.favorite_tutors