config/routes.rb
Aid::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/sign_in', :to => 'devise/sessions#new', :as => 'sign_in'
  end

  def monthly_statements_resources
    resources :monthly_statements do
      member do
        post :calculate
        get :bill
        get :payment
      end
      resources :journal_entries, :controller => 'monthly_statements/journal_entries'
    end
  end

  ########################################################### Headquarter

  namespace :hq do
    get '/' => 'home#index', :as => :root

    resources :bss do
      collection do
        get :left
      end

      member do
        get :resign
        get :leave
        post :leave
        post :activate
      end

      resources :bs_users, :controller => 'bss/bs_users' do
        member do
          match :change_password
        end
      end

      resources :students, :controller => 'bs_students', :only => [:index]

      resources :monthly_statements, :controller => 'bss/monthly_statements', :except => [:update, :destroy] do
        post 'calculate', :on => :member
        resources :adjusting_entries, :controller => 'bss/monthly_statements/adjusting_entries'
        resources :journal_entries, :controller => 'bss/monthly_statements/journal_entries', :only => [:index, :show]
      end

      resource :bank_account, :controller => 'bss/bank_accounts' do
        member do
          get :complete
        end
      end

    end
    resources :bs_users
    resources :users
    resources :tutors do
      collection do
        get :left
        get :absent
        post :create_from_app_form
      end
      member do
        match :leave
        post :come_back
        post :become_regular
        post :become_beginner
        get :change_password
        put :change_password
      end

      resource :special, :controller => :tutor_specials, :only => [:show, :update]

      resource :membership_cancellation, :controller => :tutor_membership_cancellations, :path_names => {:new => :form}

      resources :monthly_statements, :controller => 'tutors/monthly_statements' do
        post 'calculate', :on => :member
        resources :adjusting_entries, :controller => 'tutors/monthly_statements/adjusting_entries'
        resources :journal_entries, :controller => 'tutors/monthly_statements/journal_entries', :only => [:index, :show]
      end

      resources :teaching_subjects, :controller => 'tutors/teaching_subjects' do
        collection do
          put '/', action: 'update'
          get :edit
        end
      end

      resource :type, controller: :tutor_types

      resource :bank_account, :controller => 'tutors/bank_accounts'
    end

    resources :my_students, :only => :index

    resources :students do
      collection do
        get :left
        get :billing
      end
      member do
        get :history
        match :leave
        post :come_back
        get :change_password
        put :change_password
      end

      resource :membership_cancellation, :controller => :student_membership_cancellations, :path_names => {:new => :form}

      resource :address, :controller => 'students/addresses'

      resources :basic_lesson_infos, :controller => 'students/basic_lesson_infos' do
        member do
          post :extend
          post :turn_off_auto_extension
          post :turn_on_auto_extension
          post :supply
        end
        resources :lessons, :controller => 'students/basic_lesson_infos/lessons', :only => [:index, :show]
      end

      resources :optional_lessons, :controller => 'students/optional_lessons'

      resources :journal_entries, :controller => 'students/journal_entries' do
        get ':year/:month', :action => :month, :as => :month, :on => :collection
      end
      resources :ledgers, :controller => 'students/ledgers', :only => [:index] do
        collection do
          post ':year/:month/calculate', :action => :calculate
          get ':year/:month', :action => :month, :as => :month
          get ':year', :action => :year, :as => :year
        end
      end
      resources :monthly_statements, :controller => 'students/monthly_statements', :only => [:index, :show, :create, :edit] do
        member do
          post :calculate
        end
        resources :adjusting_entries, :controller => 'students/monthly_statements/adjusting_entries'
        resources :journal_entries, :controller => 'students/monthly_statements/journal_entries', :only => [:index, :show]
      end

      resources :monthly_usages, :controller => 'students/monthly_usages', :only => [:index, :show] do
        get ':year/:month', action: 'year_month', :on => :collection
        post :calculate, :on => :member
      end

      resource :coach, :controller => :student_coaches, :only => [:show]
    end

    resources :trial_students do
      member do
        get :change_password
        put :change_password
      end

      resources :lessons, :controller => :trial_student_lessons
    end

    resources :trial_lessons do
      resources :forms, :controller => :trial_lesson_forms do
        member do
          post :cancel
        end
      end
    end

    resources :parents do
      collection do
        get :left
      end
      member do
        match :leave
        get :activate
        post :activate
        get :change_password
        put :change_password
      end

      resource :membership_cancellation, :controller => :parent_membership_cancellations, :path_names => {:new => :form}
    end

    resources :coaches do
      collection do
        get :left
      end
      member do
        post :deactivate
        post :activate
        get :change_password
        put :change_password
      end
    end

    resources :tutor_interviews

    resources :lessons do
      collection do
        get :calendar
        get :under_request
        get :history
        get :pending
        get :not_started
      end
      member do
        match :cancel, :via => [:get, :post]
        get :room_as_tutor
        get :room_as_student
        get :room
        match :change_schedule
        post :cancel_request
        get :accounting
        get :updated_at
      end

      get :materials, :controller => :lesson_materials, :action => :lesson
    end

    resources :basic_lesson_infos do
      collection do
        get :pending
        get :rejected
        get :shared
        get :closed
      end
      member do
        match :stop
        post :turn_off_auto_extension
        post :turn_on_auto_extension
        post :cancel_request
        get  :close
        post :close
        get  :status
      end
      resources :forms, :controller => 'basic_lesson_infos/forms' do
        post :cancel, :on => :member
      end
      resources :lessons, :controller => 'basic_lesson_infos/lessons' do
        collection do
          post :supply
          post :cancel_selected
        end
        member do
          get :room_as_tutor
          get :room_as_student
          post :cancel
          match :change_schedule
        end
      end

      resources :students, :controller => 'basic_lesson_infos/students', :path_names => {:new => 'add'}
    end

    resources :optional_lessons do
      resources :forms, :controller => 'optional_lessons/forms' do
        member do
          post :cancel
        end
      end
    end

    resources :awards

    resources :tutor_app_forms do
      collection do
        get :processed
      end
      member do
        post :create_tutor
        get :account_created
        post :reject
      end
      resource :tutor, :controller => 'tutor_app_forms/tutors'
    end

    resources :bs_app_forms do
      collection do
        get :processed
      end
      member do
        post :create_user
        post :reject
        get  :registered
      end
      resource :bs, :controller => 'bs_app_forms/bss' do
        resource :bs_user, :controller => 'bs_app_forms/bss/bs_users', :only => [:show, :new, :create]
      end
    end

    resources :document_cameras do
      collection do
        get :yearly
        get :monthly
        get :daily
        get :file
      end
    end
    resources :messages do
      member do
        get :reply
      end
      resources :replies, controller: :message_replies
    end
    resources :my_messages do
      resources :files, controller: :my_message_files
    end
    resources :all_messages, :only => [:index, :show]

    resources :lesson_reports do
      member do
        get :prev
        get :next
      end
    end
    resources :cs_sheets
    resources :exams, :only => :index do
      collection do
        get ':grade_id/:subject_id/:year/:month/new', :action => :new
        get ':grade_id/:subject_id/:year/:month/file', :action => :file
        get ':grade_id/:subject_id/:year/:month/:paper_id', :action => :paper
        get ':grade_id/:subject_id/:year/:month', :action => :show
        post ':grade_id/:subject_id/:year/:month', :action => :create
        get ':grade_id/:subject_id/:year', :action => :year
        get ':grade_id/:subject_id', :action => :subject
        get ':grade_id', :action => :grade
      end
    end

    get :settings, :controller => :settings, :action => :index
    resource :system_settings
    resource :lesson_settings, :only => [:show, :edit, :create]
    resource :free_mode_settings
    resources :switching_payment_method_users
    resources :charge_settings

    match 'calendar(/:year(/:month))' => 'calendars#lessons', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
    resources :textbooks do
      member do
        get :image
      end
      resource :answer_book, :controller => 'textbooks/answer_books'
    end
    resources :users do
      member do
        match :change_password
      end
    end
    resources :subjects
    resources :journal_entries

    resources :monthly_statements do
      member do
        post :calculate_all
        post :calculate
        get  :yucho
      end

app/controllers/bs/monthly_statements/journal_entries_controller.rb
class Bs::MonthlyStatements::JournalEntriesController < JournalEntriesController
  bs_user_only
  before_filter :prepare_monthly_statement

  def index
    @journal_entries = @monthly_statement.journal_entries.for_list.order('created_at DESC').page(params[:page])
  end

  private

  def subject
    current_user.organization
  end
end

app/controllers/bs/monthly_statements_controller.rb
class Bs::MonthlyStatementsController < MonthlyStatementsController
  bs_user_only

  def bill
    @lesson_charges = subject.lesson_charges.of_settlement_month(@monthly_statement.year, @monthly_statement.month)
    super
  end

  def payment
    @bs = subject
    @lesson_charges = subject.lesson_charges.of_settlement_month(@monthly_statement.year, @monthly_statement.month)
    super
  end

  private

  def subject
    current_user.organization
  end

  def demandee
    current_user
  end
end

app/controllers/hq/all_messages_controller.rb
class Hq::AllMessagesController < MessagesController
  hq_user_only

  def index
    @messages = Message.order('created_at DESC').page(params[:page])

    @messages.each do |message|
      message.title = message.title.slice(0..10)+"..." if message.title.length > 10
    end
  end

  def show
    @message = Message.find(params[:id])
  end
end

app/controllers/hq/awards_controller.rb
class Hq::AwardsController < Hq::BaseController
end

app/controllers/hq/banks_controller.rb
class Hq::BanksController < BanksController
  include HqUserAccessControl
  hq_user_only
  access_control :bank
end

app/controllers/hq/base_controller.rb
class Hq::BaseController < ApplicationController
  layout 'with_sidebar'
end

app/controllers/hq/basic_lesson_infos/forms_controller.rb
class Hq::BasicLessonInfos::FormsController < BasicLessonInfoFormsController
  hq_user_only

  private

  def finish_wizard_path
    pending_hq_basic_lesson_infos_path
  end

  def redirect_path_on_cancellation
    new_hq_basic_lesson_info_path
  end
end

app/controllers/hq/basic_lesson_infos/lessons_controller.rb
class Hq::BasicLessonInfos::LessonsController < BasicLessonInfoLessonsController
  include HqUserAccessControl
  hq_user_only
  access_control :lesson
end

app/controllers/hq/basic_lesson_infos/students_controller.rb
class Hq::BasicLessonInfos::StudentsController < BasicLessonInfoStudentsController
  hq_user_only

  private

    def redirect_path
      hq_basic_lesson_info_path(@basic_lesson_info)
    end
end

app/controllers/hq/basic_lesson_infos_controller.rb
class Hq::BasicLessonInfosController < BasicLessonInfosController
  include HqUserAccessControl
  hq_user_only
  access_control :lesson
  layout 'with_sidebar'

  def new
    @basic_lesson_info = BasicLessonInfo.new # dummy
  end

  def create
    @basic_lesson_info = basic_lesson_class.new(creator:current_user)
    if @basic_lesson_info.save
      redirect_to forms_path
    else
      render action: 'new'
    end
  end

  def show
    @basic_lesson_info = current_user.basic_lesson_infos.find(params[:id])
  end

  # basic_lesson_infos/:id/supply
  def supply
    @basic_lesson_info = basic_lesson_infos.find(params[:id])
    @basic_lesson_info.supply_lessons
    redirect_to action:"show"
  end

  def stop
    @basic_lesson_info = basic_lesson_infos.find(params[:id])
    if request.get?
      @basic_lesson_info.final_day = Date.today
    else
      @basic_lesson_info.stop_in_month(params[:date][:year], params[:date][:month])
      if @basic_lesson_info.save
        redirect_to action:"show"
      else
        # do nothing
      end
    end
  end

  def turn_off_auto_extension
    @basic_lesson_info = basic_lesson_infos.find(params[:id])
    @basic_lesson_info.turn_off_auto_extension
    redirect_to action:"show"
  end

  def turn_on_auto_extension
    @basic_lesson_info = basic_lesson_infos.find(params[:id])
    @basic_lesson_info.turn_on_auto_extension
    redirect_to action:"show"
  end

  def cancel_request
    @basic_lesson_info = current_user.basic_lesson_infos.pending.find_by_id(params[:id])
    if @basic_lesson_info && @basic_lesson_info.cancel
      redirect_to({action:'pending'}, notice:t('lesson.message.request_canceled'))
    else
      redirect_to({action:'show'}, notice:t('lesson.message.failed_to_cancel'))
    end
  end

  private

    def basic_lesson_infos
      current_user.basic_lesson_infos.only_complete
    end

    def basic_lesson_class
      case params[:type]
      when 'friends' then FriendsBasicLessonInfo
      when 'shared' then SharedBasicLessonInfo
      else BasicLessonInfo
      end
    end

    def forms_path
      hq_basic_lesson_info_forms_path(@basic_lesson_info)
    end
end

app/controllers/hq/books_controller.rb
class Hq::BooksController < Hq::BaseController
  def show
  end
end

app/controllers/hq/bs_app_forms/bss/bs_users_controller.rb
class Hq::BsAppForms::Bss::BsUsersController < ApplicationController
  hq_user_only
  layout 'with_sidebar'
  before_filter :prepare_bs_app_form_and_bs

  def new
    if @bs.representative.present?
      redirect_to action:'show'
    else
      @bs_user = @bs.new_representative
    end
  end

  def show
    @bs_user = @bs.representative
  end

  def create
    @bs_user = BsUser.new(params[:bs_user]) do |bs_user|
      bs_user.organization = @bs
      bs_user.address = Address.new(params[:address]) if params[:address].present?
      bs_user.user_operating_system = UserOperatingSystem.new(params[:user_operating_system])
    end
    if @bs_user.save
      @bs.set_representative(@bs_user)
      logger.debug "@bs.representative.id = #{Bs.find(@bs.id).representative_id}"
      redirect_to action:'show'
    else
      render action:'new'
    end
  end

  private

    def prepare_bs_app_form_and_bs
      @bs_app_form = BsAppForm.find(params[:bs_app_form_id])
      @bs = @bs_app_form.bs
    end
end

app/controllers/hq/bs_app_forms/bss_controller.rb
class Hq::BsAppForms::BssController < ApplicationController
  include HqUserAccessControl
  hq_user_only
  access_control :bs
  layout 'with_sidebar'
  before_filter :prepare_bs_app_form
  after_filter :migrate_student_to_new_bs, :only => :create

  def show
    @bs = @bs_app_form.bs
  end

  def new
    @bs = @bs_app_form.new_bs
  end

  def create
    @bs = Bs.new(params[:bs]) do |bs|
      bs.address = Address.new(params[:address])
    end
    if @bs.save
      @bs_app_form.update_attribute :bs_id, @bs.id
      redirect_to new_hq_bs_app_form_bs_bs_user_path(@bs_app_form)
    else
      render action:"new"
    end
  end

  private

    def prepare_bs_app_form
      @bs_app_form = BsAppForm.find(params[:bs_app_form_id])
    end

    def migrate_student_to_new_bs
      if @bs.persisted?
        Delayed::Job.enqueue StudentsMigrationJob.new(@bs.id)
      end
    end
end

app/controllers/hq/bs_students_controller.rb
class Hq::BsStudentsController < Hq::StudentsController
  before_filter do
    @bs = Bs.find(params[:bs_id])
  end

  private

    def subject
      @bs
    end
end

app/controllers/hq/bs_users_controller.rb
class Hq::BsUsersController < ApplicationController
  hq_user_only
  layout 'with_sidebar'

  def index
    @bs_users = BsUser.order("created_at DESC")
  end

  def show
    @bs_user = BsUser.find(params[:id])
  end
end

app/controllers/hq/bss/bank_accounts_controller.rb
class Hq::Bss::BankAccountsController < BankAccountsController
  include HqUserAccessControl
  hq_user_only
  access_control :accounting
  prepend_before_filter :prepare_bs

  def show
  	@from_hq_bss = true
  	@bank_account = subject.bank_account.account
    @bank = subject.bank_account.bank
  	render controller: :bank_accounts, action: :show
  end

  private

    def subject
      @bs
    end

end

app/views/hq/monthly_statements/_breadcrumbs.html.haml
%ul.breadcrumb
  %li
    =link_to_unless_current t("titles.monthly_statements"), hq_monthly_statements_path
  -if @monthly_statement
    =breadcrumb_item t("titles.monthly_statement", month:l(@monthly_statement.date, :format => :month_year)), hq_monthly_statement_path(@monthly_statement)

app/views/hq/monthly_statements/_index_item_action.html.haml
=img_link_to 'common.detail', {action: :show, id: monthly_statement}, class: 'small'
=link_to t('yucho_account.list'), monthly_hq_yucho_accounts_path(year: monthly_statement.year, month: monthly_statement.month), class: 'btn btn-small'

app/views/hq/monthly_statements/_menu.html.haml
.button-menu
  -if @monthly_statement
    =link_to t('titles.journal_entries'), hq_monthly_statement_journal_entries_path(@monthly_statement), class: 'btn btn-small'

app/views/hq/monthly_statements/_monthly_statement.html.haml
%table.table.monthly_statement
  %thead
    %th=MonthlyStatementItem.human_attribute_name :account_item
    %th=MonthlyStatementItem.human_attribute_name :amount_of_payment
    %th=MonthlyStatementItem.human_attribute_name :billing
  %tbody
    -monthly_statement.items.each do |item|
      %tr
        %td=account_item(item)
        %td=number_to_currency(item.amount_of_payment)
        %td=number_to_currency(item.amount_of_money_received)
    / 消費税は無くなったので表示する必要はないが、消費税が加算されているデータを検出するために、
    / 金額がある場合のみ表示する。
    -if monthly_statement.tax_of_payment > 0 || monthly_statement.tax_of_money_received > 0
      %tr.tax
        %td=t('common.tax')
        %td=number_to_currency monthly_statement.tax_of_payment
        %td=number_to_currency monthly_statement.tax_of_money_received
    %tr.total
      %td=t('common.total')
      %td=number_to_currency monthly_statement.amount_of_payment
      %td=number_to_currency monthly_statement.amount_of_money_received

app/views/hq/monthly_statements/_monthly_statement_of_users.html.haml
%table.table.monthly_statement
  %thead
    %th=MonthlyStatementItem.human_attribute_name :account_item
    %th=MonthlyStatementItem.human_attribute_name :amount_of_payment
    %th=MonthlyStatementItem.human_attribute_name :billing
  %tbody
    -monthly_statement.items.each do |item|
      %tr
        %td=account_item(item)
        %td=number_to_currency(item.amount_of_money_received)
        %td=number_to_currency(item.amount_of_payment)
    / 消費税は無くなったので表示する必要はないが、消費税が加算されているデータを検出するために、
    / 金額がある場合のみ表示する。
    -if monthly_statement.tax_of_payment > 0 || monthly_statement.tax_of_money_received > 0
      %tr.tax
        %td=t('common.tax')
        %td=number_to_currency monthly_statement.tax_of_money_received
        %td=number_to_currency monthly_statement.tax_of_payment
    %tr.total
      %td=t('common.total')
      %td=number_to_currency monthly_statement.amount_of_money_received
      %td=number_to_currency monthly_statement.amount_of_payment

app/views/hq/monthly_statements/_monthly_statements.html.haml
%table.table.monthly_statements
  %thead
    %tr
      %th=MonthlyStatement.human_attribute_name :month
      %th=t('common.payment')
      %th=t('common.billing')
      %th
  %tbody
    -(1 .. 12).each do |m|
    -monthly_statement = monthly_statement_strips[m]
      %tr
        -if monthly_statement
          %td=link_to t("date.abbr_month_names")[m], {action:"show", id:monthly_statement}
          %td=number_to_currency(monthly_statement.amount_of_payment)
          %td=number_to_currency(monthly_statement.amount_of_money_received)
          %td=render 'index_item_action', monthly_statement: monthly_statement
        -else
          %td=t("date.abbr_month_names")[m]
          %td
          %td
          %td
            -if Rails.env.development?
              =link_to t('common.new'), {action: :create, year: @year, month: m}, method: :post, class: 'btn btn-small'

app/views/hq/monthly_statements/_monthly_statements_of_users.html.haml
%table.table.monthly_statements
  %thead
    %tr
      %th=MonthlyStatement.human_attribute_name :month
      %th=t('common.payment')
      %th=t('common.billing')
      %th
  %tbody
    -(1 .. 12).each do |m|
    -monthly_statement = monthly_statement_strips[m]
      %tr
        -if monthly_statement
          %td=link_to t("date.abbr_month_names")[m], {action:"show", id:monthly_statement}
          %td=number_to_currency(monthly_statement.amount_of_money_received)
          %td=number_to_currency(monthly_statement.amount_of_payment)
          %td=render 'index_item_action', monthly_statement: monthly_statement
        -else
          %td=t("date.abbr_month_names")[m]
          %td
          %td
          %td=img_link_to 'common.new', {action: :create, year: @year, month: m}, method: :post, class: 'small'

app/views/hq/monthly_statements/_show_actions.html.haml
-if current_user.can_access? :accounting, :write
  .buttons
    =link_to t('monthly_statement.calculate'), {action: :calculate_all}, method: :post, class: 'btn', remote: true
    %p.help=t('monthly_statement.period_from_to', from: monthly_statement_first_day(@monthly_statement), to: monthly_statement_last_day(@monthly_statement))

  =render 'shared/wait_screen'

app/views/hq/monthly_statements/calculate_all.js.erb
<% if @monthly_statement_calculation.errors.any? %>

var messages = [<%= @monthly_statement_calculation.errors.full_messages.map{|msg| "\"#{msg}\""}.join(', ') %>];
AID.showErrorMessages(messages);

<% else %>

var MonthlyStatementCalculation = Backbone.Model.extend({
  urlRoot: "<%= hq_monthly_statement_calculations_path %>"
});

var MonthlyStatementCalculationView = Backbone.View.extend({
  initialize: function() {
    var self = this
    _.bindAll(this)
    this.model.on('change:status', this.onStatusChanged);
    AID.startWaiting(function() {
      self.model.fetch();
    });
  },

  onStatusChanged: function() {
    if (this.model.get('status') === 'success') {
      alert("<%= t("messages.calculation_finished") %>");
    } else if (this.model.get('status') === 'error') {
      alert("<%= t('messages.calculation_failed') %>");
    } else {
      alert('???' + this.model.get('status'));
    }
    AID.stopWaiting()
    location.reload()
  }
});

var calculation = new MonthlyStatementCalculation(<%= raw @monthly_statement_calculation.to_json %>);

if (calculation.get('status') === 'new') {
  var calculationView = new MonthlyStatementCalculationView({model: calculation});
}

<% end %>

app/views/hq/monthly_statements/index.html.haml
%h1=title t('titles.monthly_statements')

=render 'menu'

=render 'year_navigation'

=render 'monthly_statements', monthly_statement_strips: @monthly_statement_strips

app/views/hq/monthly_statements/yucho.html.haml
=content_for :subheader do
  =render 'breadcrumbs'

%h1=title t('yucho_account.list')

%ul
  %li
    =link_to payments_hq_yucho_accounts_path(year: @year, month: @month), class: 'btn' do
      %i.icon-chevron-right
      =t('yucho_account.payments')
  %li
    =link_to receipts_hq_yucho_accounts_path(year: @year, month: @month), class: 'btn' do
      %i.icon-chevron-right
      =t('yucho_account.receipts')